services:
  webapp:
    build: .
    image: n8n_user_manager
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    restart: unless-stopped
